#!/bin/bash

# backup save location

backup_dir="/backup/daily/Web"
log_file="/home/centos/Documents/check_log.txt"

# check and delete old files
delete_old() {
    find "$backup_dir" -name "day-*.tar.gz" -mmin +15 -exec rm -f {} \;
}


delete_old

# Write log
echo "$(date +%M) Backup Deleted " >> "$log_file"

# Send log to Main Server
scp -r /home/centos/Documents/check_log.txt  root@192.168.125.129:/notification/check_bk_log.txt
