#!/bin/bash

# backup save location
file="/backup/daily/Web/day-$(date +%d-%m-%M).tar.gz"
backup_dir="/backup/daily/Web"


log_file="/home/centos/Documents/check_log.txt"

# Check file recieved

if [ -e "$file" ]; then
    echo "$(date): File $file exists." >> "$log_file"

else
    echo "$(date): File $file does not exist." >> "$log_file"

fi

sleep 10

# check and delete old files
delete_old() {
    find "$backup_dir" -name "day-*.tar.gz" -mmin +15 -exec rm -f {} \;
}


delete_old

# Write log
echo "$(date +%M) Backup Deleted " >> "$log_file"

# Send log to Main Server
scp -r /home/centos/Documents/check_log.txt  root@192.168.125.129:/notification/check_bk_log.txt